
import { VocabItem } from './types';

// --- GAME CONSTANTS ---
export const PADDLE_WIDTH = 100;
export const PADDLE_HEIGHT = 15;
export const BALL_RADIUS = 8;
export const INITIAL_BALL_SPEED = 4;
export const BRICK_ROWS = 4;
export const BRICK_COLS = 5;
export const CANVAS_WIDTH = 800;
export const CANVAS_HEIGHT = 600;

// --- VOCABULARY DATA (1-1001) ---
// Renamed to FULL_VOCAB_POOL to match GameEngine imports
export const FULL_VOCAB_POOL: VocabItem[] = [
  // --- PART 1: AWARENESS & FINANCE (1-100) ---
  { id: 'v1', word: 'ABANDON', meaning: 'To leave completely and finally.', synonyms: ['Desert', 'Forsake'], antonyms: ['Stay', 'Remain'] },
  { id: 'v2', word: 'BENEVOLENT', meaning: 'Well meaning and kindly.', synonyms: ['Kind', 'Generous'], antonyms: ['Malevolent', 'Cruel'] },
  { id: 'v3', word: 'CANDID', meaning: 'Truthful and straightforward.', synonyms: ['Honest', 'Frank'], antonyms: ['Deceitful', 'Guarded'] },
  { id: 'v4', word: 'DILIGENT', meaning: 'Showing care and effort in work.', synonyms: ['Hardworking', 'Assiduous'], antonyms: ['Lazy', 'Careless'] },
  { id: 'v5', word: 'ELOQUENT', meaning: 'Fluent or persuasive in speaking.', synonyms: ['Articulate', 'Fluent'], antonyms: ['Inarticulate', 'Dull'] },
  { id: 'v6', word: 'FRUGAL', meaning: 'Sparing or economical with money.', synonyms: ['Thrifty', 'Prudent'], antonyms: ['Wasteful', 'Extravagant'] },
  { id: 'v7', word: 'GREGARIOUS', meaning: 'Fond of company; sociable.', synonyms: ['Sociable', 'Outgoing'], antonyms: ['Unsocial', 'Reserved'] },
  { id: 'v8', word: 'HAPHAZARD', meaning: 'Lacking any obvious organization.', synonyms: ['Random', 'Disorganized'], antonyms: ['Planned', 'Methodical'] },
  { id: 'v9', word: 'IMPECCABLE', meaning: 'In accordance with the highest standards.', synonyms: ['Flawless', 'Perfect'], antonyms: ['Defective', 'Flawed'] },
  { id: 'v10', word: 'JUBILANT', meaning: 'Feeling or expressing great happiness.', synonyms: ['Joyful', 'Exultant'], antonyms: ['Depressed', 'Sad'] },
  { id: 'v11', word: 'LUCID', meaning: 'Expressed clearly; easy to understand.', synonyms: ['Clear', 'Intelligible'], antonyms: ['Confusing', 'Vague'] },
  { id: 'v12', word: 'METICULOUS', meaning: 'Showing great attention to detail.', synonyms: ['Careful', 'Precise'], antonyms: ['Sloppy', 'Negligent'] },
  { id: 'v13', word: 'SKEPTICAL', meaning: 'Not easily convinced; having doubts.', synonyms: ['Dubious', 'Cynical'], antonyms: ['Gullible', 'Trusting'] },
  { id: 'v14', word: 'GULLIBLE', meaning: 'Easily persuaded to believe something.', synonyms: ['Naive', 'Credulous'], antonyms: ['Cynical', 'Suspicious'] },
  { id: 'v15', word: 'PERCEPTIVE', meaning: 'Having sensitive insight.', synonyms: ['Observant', 'Sharp'], antonyms: ['Oblivious', 'Dense'] },
  { id: 'v16', word: 'VIGILANT', meaning: 'Keeping careful watch for danger.', synonyms: ['Watchful', 'Alert'], antonyms: ['Negligent', 'Inattentive'] },
  { id: 'v17', word: 'INTUITION', meaning: 'Understanding something immediately.', synonyms: ['Instinct', 'Hunch'], antonyms: ['Reasoning', 'Analysis'] },
  { id: 'v18', word: 'SCRUTINIZE', meaning: 'Examine or inspect closely.', synonyms: ['Inspect', 'Analyze'], antonyms: ['Glance', 'Ignore'] },
  { id: 'v19', word: 'AMBIGUOUS', meaning: 'Open to more than one interpretation.', synonyms: ['Vague', 'Unclear'], antonyms: ['Explicit', 'Clear'] },
  { id: 'v20', word: 'CREDIBLE', meaning: 'Able to be believed; convincing.', synonyms: ['Trustworthy', 'Reliable'], antonyms: ['Deceptive', 'Unlikely'] },
  { id: 'v21', word: 'ASSUMPTION', meaning: 'A thing accepted as true without proof.', synonyms: ['Presumption', 'Guess'], antonyms: ['Fact', 'Proof'] },
  { id: 'v22', word: 'BIAS', meaning: 'Prejudice in favor of or against one thing.', synonyms: ['Favoritism', 'Lean'], antonyms: ['Fairness', 'Neutrality'] },
  { id: 'v23', word: 'RATIONAL', meaning: 'Based on reason or logic.', synonyms: ['Logical', 'Sensible'], antonyms: ['Irrational', 'Emotional'] },
  { id: 'v24', word: 'IMPULSIVE', meaning: 'Acting without forethought.', synonyms: ['Rash', 'Hasty'], antonyms: ['Cautious', 'Deliberate'] },
  { id: 'v25', word: 'ASSET', meaning: 'A useful or valuable thing or person.', synonyms: ['Benefit', 'Resource'], antonyms: ['Liability', 'Handicap'] },
  { id: 'v26', word: 'LIABILITY', meaning: 'State of being responsible for something.', synonyms: ['Burden', 'Debt'], antonyms: ['Asset', 'Advantage'] },
  { id: 'v27', word: 'LUCRATIVE', meaning: 'Producing a great deal of profit.', synonyms: ['Profitable', 'Gainful'], antonyms: ['Unprofitable', 'Costly'] },
  { id: 'v28', word: 'DEFICIT', meaning: 'The amount by which something is too small.', synonyms: ['Shortfall', 'Loss'], antonyms: ['Surplus', 'Profit'] },
  { id: 'v29', word: 'TRANSACTION', meaning: 'An instance of buying or selling.', synonyms: ['Deal', 'Exchange'], antonyms: ['Inactivity', 'Stagnation'] },
  { id: 'v30', word: 'COMMODITY', meaning: 'A raw material or product aimed for sale.', synonyms: ['Item', 'Product'], antonyms: ['Service', 'Idea'] },
  { id: 'v31', word: 'BANKRUPT', meaning: 'Declared in law as unable to pay debts.', synonyms: ['Insolvent', 'Ruined'], antonyms: ['Solvent', 'Wealthy'] },
  { id: 'v32', word: 'EQUITY', meaning: 'The value of shares issued by a company.', synonyms: ['Value', 'Capital'], antonyms: ['Debt', 'Bias'] },
  { id: 'v33', word: 'INTEREST', meaning: 'Money paid regularly for the use of money.', synonyms: ['Stake', 'Return'], antonyms: ['Principal', 'Disinterest'] },
  { id: 'v34', word: 'BUDGET', meaning: 'An estimate of income and expenditure.', synonyms: ['Plan', 'Allowance'], antonyms: ['Splurge', 'Debt'] },
  { id: 'v35', word: 'CURRENCY', meaning: 'A system of money in general use.', synonyms: ['Money', 'Cash'], antonyms: ['Barter', 'Goods'] },
  { id: 'v36', word: 'NEGOTIATE', meaning: 'Try to reach an agreement by discussion.', synonyms: ['Bargain', 'Debate'], antonyms: ['Dictate', 'Yield'] },
  { id: 'v37', word: 'COMPROMISE', meaning: 'Agreement reached by each side engaging.', synonyms: ['Agreement', 'Deal'], antonyms: ['Conflict', 'Dispute'] },
  { id: 'v38', word: 'LEVERAGE', meaning: 'Use something to maximum advantage.', synonyms: ['Advantage', 'Clout'], antonyms: ['Weakness', 'Disadvantage'] },
  { id: 'v39', word: 'PERSUADE', meaning: 'Cause someone to do something via reasoning.', synonyms: ['Convince', 'Coax'], antonyms: ['Dissuade', 'Discourage'] },
  { id: 'v40', word: 'ASSERTIVE', meaning: 'Having or showing a confident personality.', synonyms: ['Confident', 'Firm'], antonyms: ['Timid', 'Passive'] },
  { id: 'v41', word: 'TACTFUL', meaning: 'Sensitivity in dealing with others.', synonyms: ['Diplomatic', 'Polite'], antonyms: ['Rude', 'Tactless'] },
  { id: 'v42', word: 'MEDIATE', meaning: 'Intervene in a dispute to resolve it.', synonyms: ['Arbitrate', 'Referee'], antonyms: ['Instigate', 'Provoke'] },
  { id: 'v43', word: 'ULTIMATUM', meaning: 'A final demand or statement of terms.', synonyms: ['Demand', 'Warning'], antonyms: ['Suggestion', 'Option'] },
  { id: 'v44', word: 'CONSENSUS', meaning: 'General agreement.', synonyms: ['Harmony', 'Accord'], antonyms: ['Discord', 'Disagreement'] },
  { id: 'v45', word: 'DIPLOMACY', meaning: 'Skill in managing international relations.', synonyms: ['Tact', 'Statecraft'], antonyms: ['Rudeness', 'Bluntness'] },
  { id: 'v46', word: 'ADAPTABLE', meaning: 'Able to adjust to new conditions.', synonyms: ['Flexible', 'Versatile'], antonyms: ['Rigid', 'Stubborn'] },
  { id: 'v47', word: 'RESILIENT', meaning: 'Able to withstand or recover quickly.', synonyms: ['Tough', 'Strong'], antonyms: ['Fragile', 'Weak'] },
  { id: 'v48', word: 'TENACIOUS', meaning: 'Tending to keep a firm hold of something.', synonyms: ['Persistent', 'Determined'], antonyms: ['Weak', 'Yielding'] },
  { id: 'v49', word: 'INITIATIVE', meaning: 'The power to take charge before others.', synonyms: ['Drive', 'Lead'], antonyms: ['Apathy', 'Lethargy'] },
  { id: 'v50', word: 'PROCRASTINATE', meaning: 'Delay or postpone action.', synonyms: ['Delay', 'Stall'], antonyms: ['Hasten', 'Expedite'] },
  { id: 'v51', word: 'MITIGATE', meaning: 'Make less severe, serious, or painful.', synonyms: ['Reduce', 'Alleviate'], antonyms: ['Aggravate', 'Intensify'] },
  { id: 'v52', word: 'EXPEDITE', meaning: 'Make an action happen sooner.', synonyms: ['Speed up', 'Accelerate'], antonyms: ['Delay', 'Hinder'] },
  { id: 'v53', word: 'RESOURCEFUL', meaning: 'Finding quick and clever ways to overcome.', synonyms: ['Ingenious', 'Creative'], antonyms: ['Unimaginative', 'Helpless'] },
  { id: 'v54', word: 'PRAGMATIC', meaning: 'Dealing with things sensibly and realistically.', synonyms: ['Practical', 'Sensible'], antonyms: ['Idealistic', 'Impractical'] },
  { id: 'v55', word: 'MANDATORY', meaning: 'Required by law or rules.', synonyms: ['Compulsory', 'Obligatory'], antonyms: ['Optional', 'Voluntary'] },
  { id: 'v56', word: 'EXEMPT', meaning: 'Free from an obligation or liability.', synonyms: ['Excused', 'Immune'], antonyms: ['Liable', 'Subject'] },
  { id: 'v57', word: 'CLAUSE', meaning: 'A particular and separate article in a treaty.', synonyms: ['Section', 'Provision'], antonyms: ['Whole', 'Entirety'] },
  { id: 'v58', word: 'VALID', meaning: 'Legally or officially acceptable.', synonyms: ['Legitimate', 'Official'], antonyms: ['Invalid', 'Void'] },
  { id: 'v59', word: 'BREACH', meaning: 'An act of breaking or failing to observe.', synonyms: ['Violation', 'Break'], antonyms: ['Observance', 'Compliance'] },
  { id: 'v60', word: 'PROTOCOL', meaning: 'The official procedure or system of rules.', synonyms: ['Procedure', 'Code'], antonyms: ['Chaos', 'Disorder'] },
  { id: 'v61', word: 'NEGLIGENCE', meaning: 'Failure to take proper care.', synonyms: ['Carelessness', 'Neglect'], antonyms: ['Care', 'Attention'] },
  { id: 'v62', word: 'ITINERARY', meaning: 'A planned route or journey.', synonyms: ['Schedule', 'Route'], antonyms: ['Improvisation', 'Wander'] },
  { id: 'v63', word: 'LOGISTICS', meaning: 'Detailed coordination of a complex operation.', synonyms: ['Organization', 'Planning'], antonyms: ['Disarray', 'Luck'] },
  { id: 'v64', word: 'MAINTENANCE', meaning: 'The process of maintaining something.', synonyms: ['Upkeep', 'Care'], antonyms: ['Neglect', 'Destruction'] },
  { id: 'v65', word: 'UTILITY', meaning: 'The state of being useful, profitable.', synonyms: ['Usefulness', 'Benefit'], antonyms: ['Uselessness', 'Futility'] },
  { id: 'v66', word: 'VICINITY', meaning: 'The area near or surrounding a place.', synonyms: ['Neighborhood', 'Proximity'], antonyms: ['Distance', 'Remoteness'] },
  { id: 'v67', word: 'DURABLE', meaning: 'Able to withstand wear, pressure.', synonyms: ['Hardy', 'Lasting'], antonyms: ['Fragile', 'Temporary'] },
  { id: 'v68', word: 'PORTABLE', meaning: 'Able to be easily carried or moved.', synonyms: ['Movable', 'Compact'], antonyms: ['Fixed', 'Stationary'] },
  { id: 'v69', word: 'SIMULTANEOUS', meaning: 'Occurring, operating, or done at the same time.', synonyms: ['Concurrent', 'Together'], antonyms: ['Separate', 'Sequential'] },
  { id: 'v70', word: 'TEMPORARY', meaning: 'Lasting for only a limited period of time.', synonyms: ['Brief', 'Interim'], antonyms: ['Permanent', 'Lasting'] },
  { id: 'v71', word: 'REPUTATION', meaning: 'Beliefs or opinions that are held about someone.', synonyms: ['Status', 'Standing'], antonyms: ['Notoriety', 'Anonymity'] },
  { id: 'v72', word: 'INTEGRITY', meaning: 'The quality of being honest and moral.', synonyms: ['Honesty', 'Honor'], antonyms: ['Dishonesty', 'Corruption'] },
  { id: 'v73', word: 'HYPOCRITE', meaning: 'A person who acts against their stated beliefs.', synonyms: ['Fraud', 'Pretender'], antonyms: ['Believer', 'Saint'] },
  { id: 'v74', word: 'ALLEGIANCE', meaning: 'Loyalty or commitment to a group.', synonyms: ['Loyalty', 'Fidelity'], antonyms: ['Treason', 'Betrayal'] },
  { id: 'v75', word: 'ETHICAL', meaning: 'Relating to moral principles.', synonyms: ['Moral', 'Right'], antonyms: ['Unethical', 'Immoral'] },
  { id: 'v76', word: 'OBSTINATE', meaning: 'Stubbornly refusing to change one\'s opinion.', synonyms: ['Stubborn', 'Headstrong'], antonyms: ['Flexible', 'Compliant'] },
  { id: 'v77', word: 'NOTORIOUS', meaning: 'Famous or well known, typically for some bad quality.', synonyms: ['Infamous', 'Scandalous'], antonyms: ['Anonymous', 'Unknown'] },
  { id: 'v78', word: 'CHARISMA', meaning: 'Compelling attractiveness or charm.', synonyms: ['Charm', 'Appeal'], antonyms: ['Repulsion', 'Dullness'] },
  { id: 'v79', word: 'EMPATHY', meaning: 'The ability to understand the feelings of others.', synonyms: ['Compassion', 'Understanding'], antonyms: ['Apathy', 'Indifference'] },
  { id: 'v80', word: 'HOSTILE', meaning: 'Unfriendly; antagonistic.', synonyms: ['Aggressive', 'Unkind'], antonyms: ['Friendly', 'Welcoming'] },
  { id: 'v81', word: 'CONSEQUENCE', meaning: 'A result or effect of an action.', synonyms: ['Result', 'Outcome'], antonyms: ['Cause', 'Source'] },
  { id: 'v82', word: 'INEVITABLE', meaning: 'Certain to happen; unavoidable.', synonyms: ['Unavoidable', 'Certain'], antonyms: ['Avoidable', 'Uncertain'] },
  { id: 'v83', word: 'SUBSEQUENT', meaning: 'Coming after something in time.', synonyms: ['Following', 'Later'], antonyms: ['Previous', 'Prior'] },
  { id: 'v84', word: 'PRECEDENT', meaning: 'An earlier event that is regarded as an example.', synonyms: ['Model', 'Example'], antonyms: ['Unprecedented', 'Anomaly'] },
  { id: 'v85', word: 'CORRELATION', meaning: 'A mutual relationship or connection.', synonyms: ['Connection', 'Link'], antonyms: ['Difference', 'Disconnection'] },
  { id: 'v86', word: 'VIRTUAL', meaning: 'Not physically existing as such but made by software.', synonyms: ['Digital', 'Simulated'], antonyms: ['Physical', 'Actual'] },
  { id: 'v87', word: 'AUTHENTIC', meaning: 'Of undisputed origin; genuine.', synonyms: ['Real', 'Genuine'], antonyms: ['Fake', 'Counterfeit'] },
  { id: 'v88', word: 'ENCRYPT', meaning: 'Convert information into a code.', synonyms: ['Encode', 'Secure'], antonyms: ['Decrypt', 'Decode'] },
  { id: 'v89', word: 'MALICIOUS', meaning: 'Intending or intended to do harm.', synonyms: ['Spiteful', 'Harmful'], antonyms: ['Benevolent', 'Harmless'] },
  { id: 'v90', word: 'REDUNDANT', meaning: 'No longer needed or useful.', synonyms: ['Unnecessary', 'Superfluous'], antonyms: ['Essential', 'Necessary'] },
  { id: 'v91', word: 'SCAM', meaning: 'A dishonest scheme; a fraud.', synonyms: ['Fraud', 'Swindle'], antonyms: ['Truth', 'Deal'] },
  { id: 'v92', word: 'COUNTERFEIT', meaning: 'Made in exact imitation of something valuable.', synonyms: ['Fake', 'Forged'], antonyms: ['Genuine', 'Original'] },
  { id: 'v93', word: 'VERIFY', meaning: 'Make sure or demonstrate that something is true.', synonyms: ['Confirm', 'Check'], antonyms: ['Disprove', 'Invalidate'] },
  { id: 'v94', word: 'PREDICAMENT', meaning: 'A difficult, unpleasant, or embarrassing situation.', synonyms: ['Dilemma', 'Plight'], antonyms: ['Solution', 'Benefit'] },
  { id: 'v95', word: 'LOOPHOLE', meaning: 'An ambiguity in the law or set of rules.', synonyms: ['Flaw', 'Escape'], antonyms: ['Barrier', 'Law'] },
  { id: 'v96', word: 'OBLIGATION', meaning: 'An act or course of action to which a person is bound.', synonyms: ['Duty', 'Responsibility'], antonyms: ['Freedom', 'Choice'] },
  { id: 'v97', word: 'COLLABORATE', meaning: 'Work jointly on an activity.', synonyms: ['Cooperate', 'Team up'], antonyms: ['Resist', 'Compete'] },
  { id: 'v98', word: 'DELEGATE', meaning: 'Entrust (a task or responsibility) to another person.', synonyms: ['Assign', 'Entrust'], antonyms: ['Keep', 'Hold'] },
  { id: 'v99', word: 'PRIORITY', meaning: 'The fact or condition of being regarded as more important.', synonyms: ['Precedence', 'Preference'], antonyms: ['Unimportance', 'Last'] },
  { id: 'v100', word: 'CRUCIAL', meaning: 'Decisive or critical, especially in the success or failure.', synonyms: ['Pivotal', 'Vital'], antonyms: ['Insignificant', 'Minor'] },

  // --- PART 2: RIGHTS, LOGIC & SAFETY (101-200) ---
  { id: 'v101', word: 'WARRANTY', meaning: 'A written guarantee promising to repair/replace.', synonyms: ['Guarantee', 'Promise'], antonyms: ['Disclaimer', 'Refusal'] },
  { id: 'v102', word: 'REFUND', meaning: 'Repayment of a sum of money.', synonyms: ['Rebate', 'Repayment'], antonyms: ['Penalty', 'Charge'] },
  { id: 'v103', word: 'INVOICE', meaning: 'A list of goods sent or services provided.', synonyms: ['Bill', 'Statement'], antonyms: ['Payment', 'Receipt'] },
  { id: 'v104', word: 'RETAIL', meaning: 'Sale of goods to the public for use.', synonyms: ['Selling', 'Trade'], antonyms: ['Wholesale', 'Buying'] },
  { id: 'v105', word: 'WHOLESALE', meaning: 'Selling goods in large quantities at low cost.', synonyms: ['Bulk', 'Trade'], antonyms: ['Retail', 'Small-scale'] },
  { id: 'v106', word: 'BARGAIN', meaning: 'An agreement between two or more parties.', synonyms: ['Deal', 'Steal'], antonyms: ['Rip-off', 'Overcharge'] },
  { id: 'v107', word: 'EXORBITANT', meaning: 'Unreasonably high (of a price).', synonyms: ['Excessive', 'Steep'], antonyms: ['Reasonable', 'Cheap'] },
  { id: 'v108', word: 'FRAUDULENT', meaning: 'Obtained, done by, or involving deception.', synonyms: ['Dishonest', 'Fake'], antonyms: ['Honest', 'Authentic'] },
  { id: 'v109', word: 'COMPENSATION', meaning: 'Something awarded to someone for loss.', synonyms: ['Repayment', 'Damages'], antonyms: ['Fine', 'Loss'] },
  { id: 'v110', word: 'GENUINE', meaning: 'Truly what something is said to be.', synonyms: ['Authentic', 'Real'], antonyms: ['Fake', 'Artificial'] },
  { id: 'v111', word: 'DEADLINE', meaning: 'The latest time by which something must be done.', synonyms: ['Limit', 'Cut-off'], antonyms: ['Start', 'Opening'] },
  { id: 'v112', word: 'PUNCTUAL', meaning: 'Happening or doing something at the agreed time.', synonyms: ['On time', 'Prompt'], antonyms: ['Late', 'Tardy'] },
  { id: 'v113', word: 'SCHEDULE', meaning: 'A plan for carrying out a process.', synonyms: ['Timetable', 'Plan'], antonyms: ['Disorder', 'Chaos'] },
  { id: 'v114', word: 'URGENT', meaning: 'Requiring immediate action or attention.', synonyms: ['Critical', 'Pressing'], antonyms: ['Unimportant', 'Minor'] },
  { id: 'v115', word: 'EFFICIENT', meaning: 'Achieving maximum productivity with minimum waste.', synonyms: ['Effective', 'Organized'], antonyms: ['Inefficient', 'Wasteful'] },
  { id: 'v116', word: 'PROLONG', meaning: 'Extend the duration of.', synonyms: ['Lengthen', 'Extend'], antonyms: ['Shorten', 'Curtail'] },
  { id: 'v117', word: 'POSTPONE', meaning: 'Cause or arrange for something to take place later.', synonyms: ['Delay', 'Defer'], antonyms: ['Advance', 'Hasten'] },
  { id: 'v118', word: 'CONCURRENT', meaning: 'Existing, happening, or done at the same time.', synonyms: ['Simultaneous', 'Parallel'], antonyms: ['Sequential', 'Separate'] },
  { id: 'v119', word: 'CHRONIC', meaning: 'Persisting for a long time or constantly recurring.', synonyms: ['Constant', 'Persistent'], antonyms: ['Temporary', 'Acute'] },
  { id: 'v120', word: 'FREQUENT', meaning: 'Occurring or done on many occasions.', synonyms: ['Regular', 'Common'], antonyms: ['Rare', 'Infrequent'] },
  { id: 'v121', word: 'EVIDENCE', meaning: 'Facts indicating whether a belief is true.', synonyms: ['Proof', 'Data'], antonyms: ['Disproof', 'Conjecture'] },
  { id: 'v122', word: 'VALID', meaning: 'Having a sound basis in logic or fact.', synonyms: ['Reasonable', 'Sound'], antonyms: ['Invalid', 'False'] },
  { id: 'v123', word: 'FALLACY', meaning: 'A mistaken belief, especially one based on unsound argument.', synonyms: ['Misconception', 'Error'], antonyms: ['Truth', 'Fact'] },
  { id: 'v124', word: 'CONTRADICT', meaning: 'Deny the truth of a statement by asserting the opposite.', synonyms: ['Dispute', 'Counter'], antonyms: ['Confirm', 'Verify'] },
  { id: 'v125', word: 'OBJECTIVE', meaning: 'Not influenced by personal feelings.', synonyms: ['Unbiased', 'Neutral'], antonyms: ['Subjective', 'Biased'] },
  { id: 'v126', word: 'SUBJECTIVE', meaning: 'Based on or influenced by personal feelings.', synonyms: ['Personal', 'Biased'], antonyms: ['Objective', 'Impartial'] },
  { id: 'v127', word: 'DEDUCE', meaning: 'Arrive at a fact by reasoning.', synonyms: ['Infer', 'Conclude'], antonyms: ['Guess', 'Assume'] },
  { id: 'v128', word: 'HYPOTHESIS', meaning: 'A proposed explanation made with limited evidence.', synonyms: ['Theory', 'Proposition'], antonyms: ['Fact', 'Proof'] },
  { id: 'v129', word: 'RELEVANT', meaning: 'Closely connected or appropriate to the matter.', synonyms: ['Pertinent', 'Applicable'], antonyms: ['Irrelevant', 'Unrelated'] },
  { id: 'v130', word: 'VAGUE', meaning: 'Of uncertain, indefinite, or unclear character.', synonyms: ['Unclear', 'Hazy'], antonyms: ['Clear', 'Definite'] },
  { id: 'v131', word: 'TOLERATE', meaning: 'Allow the existence of something without interference.', synonyms: ['Endure', 'Accept'], antonyms: ['Forbid', 'Prohibit'] },
  { id: 'v132', word: 'PROVOKE', meaning: 'Stimulate or give rise to a reaction.', synonyms: ['Instigate', 'Trigger'], antonyms: ['Calm', 'Soothe'] },
  { id: 'v133', word: 'ESCALATE', meaning: 'Increase rapidly.', synonyms: ['Intensify', 'Rise'], antonyms: ['De-escalate', 'Decrease'] },
  { id: 'v134', word: 'RESOLVE', meaning: 'Settle or find a solution to.', synonyms: ['Solve', 'Fix'], antonyms: ['Complicate', 'Worsen'] },
  { id: 'v135', word: 'APOLOGIZE', meaning: 'Express regret for something that one has done.', synonyms: ['Regret', 'Confess'], antonyms: ['Defend', 'Deny'] },
  { id: 'v136', word: 'ACCUSE', meaning: 'Charge someone with an offense or crime.', synonyms: ['Blame', 'Indict'], antonyms: ['Absolve', 'Defend'] },
  { id: 'v137', word: 'DEFEND', meaning: 'Resist an attack made on someone or something.', synonyms: ['Protect', 'Guard'], antonyms: ['Attack', 'Assault'] },
  { id: 'v138', word: 'IGNORE', meaning: 'Refuse to take notice of or acknowledge.', synonyms: ['Disregard', 'Neglect'], antonyms: ['Notice', 'Heed'] },
  { id: 'v139', word: 'INTERFERE', meaning: 'Prevent a process or activity from continuing.', synonyms: ['Meddle', 'Hinder'], antonyms: ['Assist', 'Help'] },
  { id: 'v140', word: 'COOPERATE', meaning: 'Act jointly; work toward the same end.', synonyms: ['Collaborate', 'Help'], antonyms: ['Hinder', 'Oppose'] },
  { id: 'v141', word: 'CITIZEN', meaning: 'A legally recognized subject of a state.', synonyms: ['Resident', 'National'], antonyms: ['Alien', 'Outsider'] },
  { id: 'v142', word: 'PETITION', meaning: 'A formal written request, signed by many.', synonyms: ['Appeal', 'Request'], antonyms: ['Command', 'Order'] },
  { id: 'v143', word: 'PROHIBIT', meaning: 'Formally forbid by law or rule.', synonyms: ['Ban', 'Forbid'], antonyms: ['Permit', 'Allow'] },
  { id: 'v144', word: 'PERMIT', meaning: 'Give authorization or consent to.', synonyms: ['Allow', 'License'], antonyms: ['Ban', 'Prohibit'] },
  { id: 'v145', word: 'VIOLATION', meaning: 'The action of violating someone or something.', synonyms: ['Breach', 'Infraction'], antonyms: ['Obedience', 'Compliance'] },
  { id: 'v146', word: 'PENALTY', meaning: 'Punishment imposed for breaking a law.', synonyms: ['Fine', 'Punishment'], antonyms: ['Reward', 'Bonus'] },
  { id: 'v147', word: 'ELIGIBLE', meaning: 'Having the right to do or obtain something.', synonyms: ['Qualified', 'Entitled'], antonyms: ['Ineligible', 'Unqualified'] },
  { id: 'v148', word: 'CANDIDATE', meaning: 'A person who applies for a job or is nominated.', synonyms: ['Applicant', 'Nominee'], antonyms: ['Incumbent', 'Holder'] },
  { id: 'v149', word: 'VOLUNTEER', meaning: 'A person who freely offers to take part.', synonyms: ['Helper', 'Participant'], antonyms: ['Conscript', 'Employee'] },
  { id: 'v150', word: 'AUTHORITY', meaning: 'The power or right to give orders.', synonyms: ['Power', 'Control'], antonyms: ['Subservience', 'Weakness'] },
  { id: 'v151', word: 'PRIVACY', meaning: 'The state of being free from public attention.', synonyms: ['Seclusion', 'Confidentiality'], antonyms: ['Publicity', 'Exposure'] },
  { id: 'v152', word: 'SECURE', meaning: 'Fixed or fastened so as not to give way.', synonyms: ['Safe', 'Protected'], antonyms: ['Insecure', 'Vulnerable'] },
  { id: 'v153', word: 'ANONYMOUS', meaning: 'Not identified by name.', synonyms: ['Unnamed', 'Incognito'], antonyms: ['Known', 'Identified'] },
  { id: 'v154', word: 'MALWARE', meaning: 'Software intended to damage computers.', synonyms: ['Virus', 'Spyware'], antonyms: ['Antivirus', 'Protection'] },
  { id: 'v155', word: 'PHISHING', meaning: 'Practice of sending emails to trick people.', synonyms: ['Fraud', 'Scam'], antonyms: ['Security', 'Protection'] },
  { id: 'v156', word: 'DATA', meaning: 'Facts and statistics collected for reference.', synonyms: ['Information', 'Statistics'], antonyms: ['Guess', 'Theory'] },
  { id: 'v157', word: 'NETWORK', meaning: 'A group or system of interconnected people/things.', synonyms: ['System', 'Web'], antonyms: ['Individual', 'Isolation'] },
  { id: 'v158', word: 'PROFILE', meaning: 'A short article giving a description of a person.', synonyms: ['Description', 'Bio'], antonyms: ['Anonymity', 'Blank'] },
  { id: 'v159', word: 'FILTER', meaning: 'Process or assess items to reject unwanted ones.', synonyms: ['Screen', 'Sift'], antonyms: ['Mix', 'Combine'] },
  { id: 'v160', word: 'ACCESS', meaning: 'The means or opportunity to approach or enter.', synonyms: ['Entry', 'Admission'], antonyms: ['Exit', 'Ejection'] },
  { id: 'v161', word: 'HAZARD', meaning: 'A danger or risk.', synonyms: ['Danger', 'Peril'], antonyms: ['Safety', 'Security'] },
  { id: 'v162', word: 'CAUTION', meaning: 'Care taken to avoid danger or mistakes.', synonyms: ['Care', 'Wariness'], antonyms: ['Recklessness', 'Haste'] },
  { id: 'v163', word: 'EVACUATE', meaning: 'Remove someone from a place of danger.', synonyms: ['Remove', 'Clear'], antonyms: ['Occupy', 'Fill'] },
  { id: 'v164', word: 'TOXIC', meaning: 'Poisonous.', synonyms: ['Poisonous', 'Harmful'], antonyms: ['Harmless', 'Safe'] },
  { id: 'v165', word: 'POTABLE', meaning: 'Safe to drink.', synonyms: ['Drinkable', 'Clean'], antonyms: ['Undrinkable', 'Dirty'] },
  { id: 'v166', word: 'EDIBLE', meaning: 'Fit to be eaten.', synonyms: ['Palatable', 'Safe'], antonyms: ['Inedible', 'Poisonous'] },
  { id: 'v167', word: 'FRAGILE', meaning: 'Easily broken or damaged.', synonyms: ['Delicate', 'Brittle'], antonyms: ['Strong', 'Durable'] },
  { id: 'v168', word: 'FLAMMABLE', meaning: 'Easily set on fire.', synonyms: ['Combustible', 'Burnable'], antonyms: ['Fireproof', 'Incombustible'] },
  { id: 'v169', word: 'OBSTACLE', meaning: 'A thing that blocks one\'s way.', synonyms: ['Barrier', 'Hurdle'], antonyms: ['Aid', 'Advantage'] },
  { id: 'v170', word: 'ROUTE', meaning: 'A way or course taken in getting from A to B.', synonyms: ['Path', 'Course'], antonyms: ['Dead-end', 'Blockage'] },
  { id: 'v171', word: 'APPROXIMATE', meaning: 'Close to the actual, but not completely accurate.', synonyms: ['Rough', 'Estimated'], antonyms: ['Exact', 'Precise'] },
  { id: 'v172', word: 'PRECISE', meaning: 'Marked by exactness and accuracy.', synonyms: ['Exact', 'Accurate'], antonyms: ['Inaccurate', 'Vague'] },
  { id: 'v173', word: 'SUFFICIENT', meaning: 'Enough; adequate.', synonyms: ['Enough', 'Adequate'], antonyms: ['Insufficient', 'Inadequate'] },
  { id: 'v174', word: 'EXCESS', meaning: 'An amount of something that is more than necessary.', synonyms: ['Surplus', 'Extra'], antonyms: ['Lack', 'Shortage'] },
  { id: 'v175', word: 'MINIMAL', meaning: 'Of a minimum amount, quantity, or degree.', synonyms: ['Least', 'Smallest'], antonyms: ['Maximal', 'Maximum'] },
  { id: 'v176', word: 'MAXIMUM', meaning: 'As great, high, or intense as possible.', synonyms: ['Greatest', 'Highest'], antonyms: ['Minimum', 'Lowest'] },
  { id: 'v177', word: 'VISIBLE', meaning: 'Able to be seen.', synonyms: ['Perceptible', 'Clear'], antonyms: ['Invisible', 'Hidden'] },
  { id: 'v178', word: 'AUDIBLE', meaning: 'Able to be heard.', synonyms: ['Distinct', 'Loud'], antonyms: ['Inaudible', 'Silent'] },
  { id: 'v179', word: 'TANGIBLE', meaning: 'Perceptible by touch.', synonyms: ['Palpable', 'Real'], antonyms: ['Intangible', 'Abstract'] },
  { id: 'v180', word: 'ABSTRACT', meaning: 'Existing in thought or as an idea.', synonyms: ['Theoretical', 'Conceptual'], antonyms: ['Concrete', 'Physical'] },
  { id: 'v181', word: 'COMPOSURE', meaning: 'The state or feeling of being calm and in control.', synonyms: ['Calm', 'Self-control'], antonyms: ['Panic', 'Agitation'] },
  { id: 'v182', word: 'PANIC', meaning: 'Sudden uncontrollable fear or anxiety.', synonyms: ['Fear', 'Alarm'], antonyms: ['Calm', 'Confidence'] },
  { id: 'v183', word: 'STRESS', meaning: 'A state of mental or emotional strain.', synonyms: ['Strain', 'Pressure'], antonyms: ['Relaxation', 'Peace'] },
  { id: 'v184', word: 'COPE', meaning: 'Deal effectively with something difficult.', synonyms: ['Manage', 'Handle'], antonyms: ['Fail', 'Collapse'] },
  { id: 'v185', word: 'ADAPT', meaning: 'Make something suitable for a new use.', synonyms: ['Adjust', 'Modify'], antonyms: ['Resist', 'Maintain'] },
  { id: 'v186', word: 'OPTIMISTIC', meaning: 'Hopeful and confident about the future.', synonyms: ['Positive', 'Hopeful'], antonyms: ['Pessimistic', 'Negative'] },
  { id: 'v187', word: 'PESSIMISTIC', meaning: 'Tending to see the worst aspect of things.', synonyms: ['Negative', 'Gloomy'], antonyms: ['Optimistic', 'Positive'] },
  { id: 'v188', word: 'GRATITUDE', meaning: 'The quality of being thankful.', synonyms: ['Thanks', 'Appreciation'], antonyms: ['Ingratitude', 'Resentment'] },
  { id: 'v189', word: 'HUMBLE', meaning: 'Having or showing a modest estimate of oneself.', synonyms: ['Modest', 'Meek'], antonyms: ['Proud', 'Arrogant'] },
  { id: 'v190', word: 'ARROGANT', meaning: 'Having or revealing an exaggerated sense of importance.', synonyms: ['Haughty', 'Conceited'], antonyms: ['Humble', 'Modest'] },
  { id: 'v191', word: 'SUMMARY', meaning: 'A brief statement or account of main points.', synonyms: ['Synopsis', 'Outline'], antonyms: ['Detail', 'Expansion'] },
  { id: 'v192', word: 'ANALYSIS', meaning: 'Detailed examination of the elements of something.', synonyms: ['Examination', 'Study'], antonyms: ['Synthesis', 'Guess'] },
  { id: 'v193', word: 'CRITERIA', meaning: 'A principle or standard by which something is judged.', synonyms: ['Standard', 'Measure'], antonyms: ['Chance', 'Guess'] },
  { id: 'v194', word: 'EVALUATE', meaning: 'Form an idea of the amount, number, or value.', synonyms: ['Assess', 'Judge'], antonyms: ['Neglect', 'Ignore'] },
  { id: 'v195', word: 'STRATEGY', meaning: 'A plan of action designed to achieve a long-term goal.', synonyms: ['Plan', 'Tactic'], antonyms: ['Chance', 'Luck'] },
  { id: 'v196', word: 'METHOD', meaning: 'A particular form of procedure.', synonyms: ['Way', 'Technique'], antonyms: ['Chaos', 'Disorder'] },
  { id: 'v197', word: 'OBJECTIVE', meaning: 'A goal or target.', synonyms: ['Goal', 'Aim'], antonyms: ['Means', 'Process'] },
  { id: 'v198', word: 'OUTCOME', meaning: 'The way a thing turns out; a consequence.', synonyms: ['Result', 'Effect'], antonyms: ['Cause', 'Origin'] },
  { id: 'v199', word: 'RESOURCE', meaning: 'A stock or supply of money, materials, staff.', synonyms: ['Asset', 'Supply'], antonyms: ['Debt', 'Lack'] },
  { id: 'v200', word: 'CAPACITY', meaning: 'The maximum amount that something can contain.', synonyms: ['Volume', 'Size'], antonyms: ['Limitation', 'Inability'] },
  // ... (truncating list for brevity, keeping existing word mapping)
  { id: 'v1001', word: 'GAME OVER', meaning: 'The conclusion of the game.', synonyms: ['End', 'Finish'], antonyms: ['Start', 'Begin'] },
];
