
import { VocabItem } from './types.ts';

// --- GAME CONSTANTS ---

export const PADDLE_WIDTH = 140;
export const PADDLE_HEIGHT = 18;
export const BALL_RADIUS = 10;
export const INITIAL_BALL_SPEED = 5;
export const BRICK_ROWS = 3;
export const BRICK_COLS = 5;
export const CANVAS_WIDTH = 1024; // 16:9 base width
export const CANVAS_HEIGHT = 576; // 16:9 base height

// --- VOCABULARY DATA (1-1001) ---

export const FULL_VOCAB_POOL: VocabItem[] = [
  // --- PART 1: AWARENESS & FINANCE (1-100) ---
  { id: 'v1', word: 'ABANDON', meaning: 'To leave completely and finally.', synonyms: ['Desert', 'Forsake'], antonyms: ['Stay', 'Remain'] },
  { id: 'v2', word: 'BENEVOLENT', meaning: 'Well meaning and kindly.', synonyms: ['Kind', 'Generous'], antonyms: ['Malevolent', 'Cruel'] },
  { id: 'v3', word: 'CANDID', meaning: 'Truthful and straightforward.', synonyms: ['Honest', 'Frank'], antonyms: ['Deceitful', 'Guarded'] },
  { id: 'v4', word: 'DILIGENT', meaning: 'Showing care and effort in work.', synonyms: ['Hardworking', 'Assiduous'], antonyms: ['Lazy', 'Careless'] },
  { id: 'v5', word: 'ELOQUENT', meaning: 'Fluent or persuasive in speaking.', synonyms: ['Articulate', 'Fluent'], antonyms: ['Inarticulate', 'Dull'] },
  { id: 'v6', word: 'FRUGAL', meaning: 'Sparing or economical with money.', synonyms: ['Thrifty', 'Prudent'], antonyms: ['Wasteful', 'Extravagant'] },
  { id: 'v7', word: 'GREGARIOUS', meaning: 'Fond of company; sociable.', synonyms: ['Sociable', 'Outgoing'], antonyms: ['Unsocial', 'Reserved'] },
  { id: 'v8', word: 'HAPHAZARD', meaning: 'Lacking any obvious organization.', synonyms: ['Random', 'Disorganized'], antonyms: ['Planned', 'Methodical'] },
  { id: 'v9', word: 'IMPECCABLE', meaning: 'In accordance with the highest standards.', synonyms: ['Flawless', 'Perfect'], antonyms: ['Defective', 'Flawed'] },
  { id: 'v10', word: 'JUBILANT', meaning: 'Feeling or expressing great happiness.', synonyms: ['Joyful', 'Exultant'], antonyms: ['Depressed', 'Sad'] },
  { id: 'v11', word: 'LUCID', meaning: 'Expressed clearly; easy to understand.', synonyms: ['Clear', 'Intelligible'], antonyms: ['Confusing', 'Vague'] },
  { id: 'v12', word: 'METICULOUS', meaning: 'Showing great attention to detail.', synonyms: ['Careful', 'Precise'], antonyms: ['Sloppy', 'Negligent'] },
  { id: 'v13', word: 'SKEPTICAL', meaning: 'Not easily convinced; having doubts.', synonyms: ['Dubious', 'Cynical'], antonyms: ['Gullible', 'Trusting'] },
  { id: 'v14', word: 'GULLIBLE', meaning: 'Easily persuaded to believe something.', synonyms: ['Naive', 'Credulous'], antonyms: ['Cynical', 'Suspicious'] },
  { id: 'v15', word: 'PERCEPTIVE', meaning: 'Having sensitive insight.', synonyms: ['Observant', 'Sharp'], antonyms: ['Oblivious', 'Dense'] },
  { id: 'v16', word: 'VIGILANT', meaning: 'Keeping careful watch for danger.', synonyms: ['Watchful', 'Alert'], antonyms: ['Negligent', 'Inattentive'] },
  { id: 'v17', word: 'INTUITION', meaning: 'Understanding something immediately.', synonyms: ['Instinct', 'Hunch'], antonyms: ['Reasoning', 'Analysis'] },
  { id: 'v18', word: 'SCRUTINIZE', meaning: 'Examine or inspect closely.', synonyms: ['Inspect', 'Analyze'], antonyms: ['Glance', 'Ignore'] },
  { id: 'v19', word: 'AMBIGUOUS', meaning: 'Open to more than one interpretation.', synonyms: ['Vague', 'Unclear'], antonyms: ['Explicit', 'Clear'] },
  { id: 'v20', word: 'CREDIBLE', meaning: 'Able to be believed; convincing.', synonyms: ['Trustworthy', 'Reliable'], antonyms: ['Deceptive', 'Unlikely'] },
  { id: 'v21', word: 'ASSUMPTION', meaning: 'A thing accepted as true without proof.', synonyms: ['Presumption', 'Guess'], antonyms: ['Fact', 'Proof'] },
  { id: 'v22', word: 'BIAS', meaning: 'Prejudice in favor of or against one thing.', synonyms: ['Favoritism', 'Lean'], antonyms: ['Fairness', 'Neutrality'] },
  { id: 'v23', word: 'RATIONAL', meaning: 'Based on reason or logic.', synonyms: ['Logical', 'Sensible'], antonyms: ['Irrational', 'Emotional'] },
  { id: 'v24', word: 'IMPULSIVE', meaning: 'Acting without forethought.', synonyms: ['Rash', 'Hasty'], antonyms: ['Cautious', 'Deliberate'] },
  { id: 'v25', word: 'ASSET', meaning: 'A useful or valuable thing or person.', synonyms: ['Benefit', 'Resource'], antonyms: ['Liability', 'Handicap'] },
  { id: 'v26', word: 'LIABILITY', meaning: 'State of being responsible for something.', synonyms: ['Burden', 'Debt'], antonyms: ['Asset', 'Advantage'] },
  { id: 'v27', word: 'LUCRATIVE', meaning: 'Producing a great deal of profit.', synonyms: ['Profitable', 'Gainful'], antonyms: ['Unprofitable', 'Costly'] },
  { id: 'v28', word: 'DEFICIT', meaning: 'The amount by which something is too small.', synonyms: ['Shortfall', 'Loss'], antonyms: ['Surplus', 'Profit'] },
  { id: 'v29', word: 'TRANSACTION', meaning: 'An instance of buying or selling.', synonyms: ['Deal', 'Exchange'], antonyms: ['Inactivity', 'Stagnation'] },
  { id: 'v30', word: 'COMMODITY', meaning: 'A raw material or product aimed for sale.', synonyms: ['Item', 'Product'], antonyms: ['Service', 'Idea'] },
  { id: 'v31', word: 'BANKRUPT', meaning: 'Declared in law as unable to pay debts.', synonyms: ['Insolvent', 'Ruined'], antonyms: ['Solvent', 'Wealthy'] },
  { id: 'v32', word: 'EQUITY', meaning: 'The value of shares issued by a company.', synonyms: ['Value', 'Capital'], antonyms: ['Debt', 'Bias'] },
  { id: 'v33', word: 'INTEREST', meaning: 'Money paid regularly for the use of money.', synonyms: ['Stake', 'Return'], antonyms: ['Principal', 'Disinterest'] },
  { id: 'v34', word: 'BUDGET', meaning: 'An estimate of income and expenditure.', synonyms: ['Plan', 'Allowance'], antonyms: ['Splurge', 'Debt'] },
  { id: 'v35', word: 'CURRENCY', meaning: 'A system of money in general use.', synonyms: ['Money', 'Cash'], antonyms: ['Barter', 'Goods'] },
  { id: 'v36', word: 'NEGOTIATE', meaning: 'Try to reach an agreement by discussion.', synonyms: ['Bargain', 'Debate'], antonyms: ['Dictate', 'Yield'] },
  { id: 'v37', word: 'COMPROMISE', meaning: 'Agreement reached by each side engaging.', synonyms: ['Agreement', 'Deal'], antonyms: ['Conflict', 'Dispute'] },
  { id: 'v38', word: 'LEVERAGE', meaning: 'Use something to maximum advantage.', synonyms: ['Advantage', 'Clout'], antonyms: ['Weakness', 'Disadvantage'] },
  { id: 'v39', word: 'PERSUADE', meaning: 'Cause someone to do something via reasoning.', synonyms: ['Convince', 'Coax'], antonyms: ['Dissuade', 'Discourage'] },
  { id: 'v40', word: 'ASSERTIVE', meaning: 'Having or showing a confident personality.', synonyms: ['Confident', 'Firm'], antonyms: ['Timid', 'Passive'] },
  { id: 'v41', word: 'TACTFUL', meaning: 'Sensitivity in dealing with others.', synonyms: ['Diplomatic', 'Polite'], antonyms: ['Rude', 'Tactless'] },
  { id: 'v42', word: 'MEDIATE', meaning: 'Intervene in a dispute to resolve it.', synonyms: ['Arbitrate', 'Referee'], antonyms: ['Instigate', 'Provoke'] },
  { id: 'v43', word: 'ULTIMATUM', meaning: 'A final demand or statement of terms.', synonyms: ['Demand', 'Warning'], antonyms: ['Suggestion', 'Option'] },
  { id: 'v44', word: 'CONSENSUS', meaning: 'General agreement.', synonyms: ['Harmony', 'Accord'], antonyms: ['Discord', 'Disagreement'] },
  { id: 'v45', word: 'DIPLOMACY', meaning: 'Skill in managing international relations.', synonyms: ['Tact', 'Statecraft'], antonyms: ['Rudeness', 'Bluntness'] },
  { id: 'v46', word: 'ADAPTABLE', meaning: 'Able to adjust to new conditions.', synonyms: ['Flexible', 'Versatile'], antonyms: ['Rigid', 'Stubborn'] },
  { id: 'v47', word: 'RESILIENT', meaning: 'Able to withstand or recover quickly.', synonyms: ['Tough', 'Strong'], antonyms: ['Fragile', 'Weak'] },
  { id: 'v48', word: 'TENACIOUS', meaning: 'Tending to keep a firm hold of something.', synonyms: ['Persistent', 'Determined'], antonyms: ['Weak', 'Yielding'] },
  { id: 'v49', word: 'INITIATIVE', meaning: 'The power to take charge before others.', synonyms: ['Drive', 'Lead'], antonyms: ['Apathy', 'Lethargy'] },
  { id: 'v50', word: 'PROCRASTINATE', meaning: 'Delay or postpone action.', synonyms: ['Delay', 'Stall'], antonyms: ['Hasten', 'Expedite'] },
  { id: 'v51', word: 'MITIGATE', meaning: 'Make less severe, serious, or painful.', synonyms: ['Reduce', 'Alleviate'], antonyms: ['Aggravate', 'Intensify'] },
  { id: 'v52', word: 'EXPEDITE', meaning: 'Make an action happen sooner.', synonyms: ['Speed up', 'Accelerate'], antonyms: ['Delay', 'Hinder'] },
  { id: 'v53', word: 'RESOURCEFUL', meaning: 'Finding quick and clever ways to overcome.', synonyms: ['Ingenious', 'Creative'], antonyms: ['Unimaginative', 'Helpless'] },
  { id: 'v54', word: 'PRAGMATIC', meaning: 'Dealing with things sensibly and realistically.', synonyms: ['Practical', 'Sensible'], antonyms: ['Idealistic', 'Impractical'] },
  { id: 'v55', word: 'MANDATORY', meaning: 'Required by law or rules.', synonyms: ['Compulsory', 'Obligatory'], antonyms: ['Optional', 'Voluntary'] },
  { id: 'v56', word: 'EXEMPT', meaning: 'Free from an obligation or liability.', synonyms: ['Excused', 'Immune'], antonyms: ['Liable', 'Subject'] },
  { id: 'v57', word: 'CLAUSE', meaning: 'A particular and separate article in a treaty.', synonyms: ['Section', 'Provision'], antonyms: ['Whole', 'Entirety'] },
  { id: 'v58', word: 'VALID', meaning: 'Legally or officially acceptable.', synonyms: ['Legitimate', 'Official'], antonyms: ['Invalid', 'Void'] },
  { id: 'v59', word: 'BREACH', meaning: 'An act of breaking or failing to observe.', synonyms: ['Violation', 'Break'], antonyms: ['Observance', 'Compliance'] },
  { id: 'v60', word: 'PROTOCOL', meaning: 'The official procedure or system of rules.', synonyms: ['Procedure', 'Code'], antonyms: ['Chaos', 'Disorder'] },
  { id: 'v61', word: 'NEGLIGENCE', meaning: 'Failure to take proper care.', synonyms: ['Carelessness', 'Neglect'], antonyms: ['Care', 'Attention'] },
  { id: 'v62', word: 'ITINERARY', meaning: 'A planned route or journey.', synonyms: ['Schedule', 'Route'], antonyms: ['Improvisation', 'Wander'] },
  { id: 'v63', word: 'LOGISTICS', meaning: 'Detailed coordination of a complex operation.', synonyms: ['Organization', 'Planning'], antonyms: ['Disarray', 'Luck'] },
  { id: 'v64', word: 'MAINTENANCE', meaning: 'The process of maintaining something.', synonyms: ['Upkeep', 'Care'], antonyms: ['Neglect', 'Destruction'] },
  { id: 'v65', word: 'UTILITY', meaning: 'The state of being useful, profitable.', synonyms: ['Usefulness', 'Benefit'], antonyms: ['Uselessness', 'Futility'] },
  { id: 'v66', word: 'VICINITY', meaning: 'The area near or surrounding a place.', synonyms: ['Neighborhood', 'Proximity'], antonyms: ['Distance', 'Remoteness'] },
  { id: 'v67', word: 'DURABLE', meaning: 'Able to withstand wear, pressure.', synonyms: ['Hardy', 'Lasting'], antonyms: ['Fragile', 'Temporary'] },
  { id: 'v68', word: 'PORTABLE', meaning: 'Able to be easily carried or moved.', synonyms: ['Movable', 'Compact'], antonyms: ['Fixed', 'Stationary'] },
  { id: 'v69', word: 'SIMULTANEOUS', meaning: 'Occurring, operating, or done at the same time.', synonyms: ['Concurrent', 'Together'], antonyms: ['Separate', 'Sequential'] },
  { id: 'v70', word: 'TEMPORARY', meaning: 'Lasting for only a limited period of time.', synonyms: ['Brief', 'Interim'], antonyms: ['Permanent', 'Lasting'] },
  { id: 'v71', word: 'REPUTATION', meaning: 'Beliefs or opinions that are held about someone.', synonyms: ['Status', 'Standing'], antonyms: ['Notoriety', 'Anonymity'] },
  { id: 'v72', word: 'INTEGRITY', meaning: 'The quality of being honest and moral.', synonyms: ['Honesty', 'Honor'], antonyms: ['Dishonesty', 'Corruption'] },
  { id: 'v73', word: 'HYPOCRITE', meaning: 'A person who acts against their stated beliefs.', synonyms: ['Fraud', 'Pretender'], antonyms: ['Believer', 'Saint'] },
  { id: 'v74', word: 'ALLEGIANCE', meaning: 'Loyalty or commitment to a group.', synonyms: ['Loyalty', 'Fidelity'], antonyms: ['Treason', 'Betrayal'] },
  { id: 'v75', word: 'ETHICAL', meaning: 'Relating to moral principles.', synonyms: ['Moral', 'Right'], antonyms: ['Unethical', 'Immoral'] },
  { id: 'v76', word: 'OBSTINATE', meaning: 'Stubbornly refusing to change one\'s opinion.', synonyms: ['Stubborn', 'Headstrong'], antonyms: ['Flexible', 'Compliant'] },
  { id: 'v77', word: 'NOTORIOUS', meaning: 'Famous or well known, typically for some bad quality.', synonyms: ['Infamous', 'Scandalous'], antonyms: ['Anonymous', 'Unknown'] },
  { id: 'v78', word: 'CHARISMA', meaning: 'Compelling attractiveness or charm.', synonyms: ['Charm', 'Appeal'], antonyms: ['Repulsion', 'Dullness'] },
  { id: 'v79', word: 'EMPATHY', meaning: 'The ability to understand the feelings of others.', synonyms: ['Compassion', 'Understanding'], antonyms: ['Apathy', 'Indifference'] },
  { id: 'v80', word: 'HOSTILE', meaning: 'Unfriendly; antagonistic.', synonyms: ['Aggressive', 'Unkind'], antonyms: ['Friendly', 'Welcoming'] },
  { id: 'v81', word: 'CONSEQUENCE', meaning: 'A result or effect of an action.', synonyms: ['Result', 'Outcome'], antonyms: ['Cause', 'Source'] },
  { id: 'v82', word: 'INEVITABLE', meaning: 'Certain to happen; unavoidable.', synonyms: ['Unavoidable', 'Certain'], antonyms: ['Avoidable', 'Uncertain'] },
  { id: 'v83', word: 'SUBSEQUENT', meaning: 'Coming after something in time.', synonyms: ['Following', 'Later'], antonyms: ['Previous', 'Prior'] },
  { id: 'v84', word: 'PRECEDENT', meaning: 'An earlier event that is regarded as an example.', synonyms: ['Model', 'Example'], antonyms: ['Unprecedented', 'Anomaly'] },
  { id: 'v85', word: 'CORRELATION', meaning: 'A mutual relationship or connection.', synonyms: ['Connection', 'Link'], antonyms: ['Difference', 'Disconnection'] },
  { id: 'v86', word: 'VIRTUAL', meaning: 'Not physically existing as such but made by software.', synonyms: ['Digital', 'Simulated'], antonyms: ['Physical', 'Actual'] },
  { id: 'v87', word: 'AUTHENTIC', meaning: 'Of undisputed origin; genuine.', synonyms: ['Real', 'Genuine'], antonyms: ['Fake', 'Counterfeit'] },
  { id: 'v88', word: 'ENCRYPT', meaning: 'Convert information into a code.', synonyms: ['Encode', 'Secure'], antonyms: ['Decrypt', 'Decode'] },
  { id: 'v89', word: 'MALICIOUS', meaning: 'Intending or intended to do harm.', synonyms: ['Spiteful', 'Harmful'], antonyms: ['Benevolent', 'Harmless'] },
  { id: 'v90', word: 'REDUNDANT', meaning: 'No longer needed or useful.', synonyms: ['Unnecessary', 'Superfluous'], antonyms: ['Essential', 'Necessary'] },
  { id: 'v91', word: 'SCAM', meaning: 'A dishonest scheme; a fraud.', synonyms: ['Fraud', 'Swindle'], antonyms: ['Truth', 'Deal'] },
  { id: 'v92', word: 'COUNTERFEIT', meaning: 'Made in exact imitation of something valuable.', synonyms: ['Fake', 'Forged'], antonyms: ['Genuine', 'Original'] },
  { id: 'v93', word: 'VERIFY', meaning: 'Make sure or demonstrate that something is true.', synonyms: ['Confirm', 'Check'], antonyms: ['Disprove', 'Invalidate'] },
  { id: 'v94', word: 'PREDICAMENT', meaning: 'A difficult, unpleasant, or embarrassing situation.', synonyms: ['Dilemma', 'Plight'], antonyms: ['Solution', 'Benefit'] },
  { id: 'v95', word: 'LOOPHOLE', meaning: 'An ambiguity in the law or set of rules.', synonyms: ['Flaw', 'Escape'], antonyms: ['Barrier', 'Law'] },
  { id: 'v96', word: 'OBLIGATION', meaning: 'An act or course of action to which a person is bound.', synonyms: ['Duty', 'Responsibility'], antonyms: ['Freedom', 'Choice'] },
  { id: 'v97', word: 'COLLABORATE', meaning: 'Work jointly on an activity.', synonyms: ['Cooperate', 'Team up'], antonyms: ['Resist', 'Compete'] },
  { id: 'v98', word: 'DELEGATE', meaning: 'Entrust (a task or responsibility) to another person.', synonyms: ['Assign', 'Entrust'], antonyms: ['Keep', 'Hold'] },
  { id: 'v99', word: 'PRIORITY', meaning: 'The fact or condition of being regarded as more important.', synonyms: ['Precedence', 'Preference'], antonyms: ['Unimportance', 'Last'] },
  { id: 'v100', word: 'CRUCIAL', meaning: 'Decisive or critical, especially in the success or failure.', synonyms: ['Pivotal', 'Vital'], antonyms: ['Insignificant', 'Minor'] },
  { id: 'v1001', word: 'GAME OVER', meaning: 'The conclusion of the game.', synonyms: ['End', 'Finish'], antonyms: ['Start', 'Begin'] },
];
